#
# Module manifest for module 'vNugglets.Utility'
#
# Generated by: Matt Boren
#
# Generated on: 12/6/2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'vNuggletsUtilityMod.psm1'

# Version number of this module.
ModuleVersion = '1.1.0'

# ID used to uniquely identify this module
GUID = 'a22ca8fe-3739-463f-b8dd-4d5d2c9ffec4'

# Author of this module
Author = 'Matt Boren'

# Company or vendor of this module
CompanyName = 'vNugglets.com'

# Copyright statement for this module
Copyright = 'MIT License'

# Description of the functionality provided by this module
Description = 'Module with the functions that have previously been scattered about the web by the vNugglets team (particularly, at vNugglets.com'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '4.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('vNuggletsUtilityMod_functions.ps1', 
               'vNugglets_SupportingFunctions.ps1')

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
# CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module
# AliasesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = 'vNugglets.Utility.psd1', 'vNuggletsUtilityMod.psm1', 
               'vNuggletsUtilityMod_functions.ps1', 
               'vNugglets_SupportingFunctions.ps1', 
               'about_vNugglets.Utility.help.txt'

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


